# Generated by Django 4.0.10 on 2024-01-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.workflow'),
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from+', to='core.node')),
                ('n_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to+', to='core.node')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workflow')),
            ],
        ),
    ]
