# Generated by Django 4.0.10 on 2024-01-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_node_workflow_edge'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('n_from', 'n_to'), name='unique_edge'),
        ),
    ]
