# Generated by Django 4.0.10 on 2024-01-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_messageholder_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageholder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=16),
        ),
    ]
