# Generated by Django 4.0.10 on 2024-01-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_messageholder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageholder',
            name='is_active',
        ),
    ]
