# Generated by Django 4.0.10 on 2024-01-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_messageholder_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_finishing_node',
            field=models.BooleanField(default=False),
        ),
    ]
