# Generated by Django 4.0.10 on 2024-01-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_message_issuer_alter_workflow_create_by'),
        ('core', '0012_history_history_core_histor_content_4ad575_idx'),
    ]

    operations = [
    ]
